# Assignment for Week 1

## Purpose:      
This assignment is intended to help you do the following:       
1.	Open a GitHub account for your own use and for your career advancement (if you already do not have one).     
2.	Submit information and code in GitHub following best practices from the Udacity course.     
3.	Explore a dataset thoroughly.      
4.	Find and print descriptive information from the dataset.

## Action Items:           
Open a GitHub account to submit your work. If you are new to GitHub, follow the videos and instructions on the following link to understand how to post things on GitHub and start your own account. https://blog.udacity.com/2015/06/a-beginners-git-github-tutorial.html and/or https://guides.github.com/activities/hello-world/     

1.   Select the dataset of your choice from the list 
provided <a href="https://github.com/frankData612/data_612">here.</a>   
2.   Load the dataset using Jupyter notebook and explore the data by using the following.


-	Show the .head() and .tail() of the data set. Specify the number of rows to print using .head() and .tail().      
-	Print the column names.      
-	Print to see what is the type of your data set    
-	Check number of rows and columns.
-	Use groupby() and find the mean on your selected colum/s.
-	Add a README file in GitHub where you explain everything you did.

In [12]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/frankData612/data_612/master/stock_data/stocks_yahoo.csv")
print(df.head())
print(df.tail())

   no         date  ... Dividend Yield  1Y target est
0   1  Nov 21 2019  ...      N/A (N/A)        1487.52
1   2  Nov 21 2019  ...      N/A (N/A)        1459.33
2   3  Nov 21 2019  ...   6.48 (4.86%)         148.30
3   4  Nov 21 2019  ...   2.04 (1.36%)         160.16
4   5  Nov 21 2019  ...   3.08 (1.16%)         257.21

[5 rows x 19 columns]
          no         date  ... Dividend Yield  1Y target est
67900  67901  Apr 28 2020  ...      N/A (N/A)          12.83
67901  67902  Apr 28 2020  ...   0.44 (1.49%)          33.33
67902  67903  Apr 28 2020  ...      N/A (N/A)          11.50
67903  67904  Apr 28 2020  ...      N/A (N/A)          67.67
67904  67905  Apr 28 2020  ...      N/A (N/A)          67.62

[5 rows x 19 columns]

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [13]:
df.head(10)

   no         date  ... Dividend Yield  1Y target est
0   1  Nov 21 2019  ...      N/A (N/A)        1487.52
1   2  Nov 21 2019  ...      N/A (N/A)        1459.33
2   3  Nov 21 2019  ...   6.48 (4.86%)         148.30
3   4  Nov 21 2019  ...   2.04 (1.36%)         160.16
4   5  Nov 21 2019  ...   3.08 (1.16%)         257.21
5   6  Nov 21 2019  ...      N/A (N/A)        2183.86
6   7  Nov 21 2019  ...      N/A (N/A)            NaN
7   8  Nov 21 2019  ...   0.96 (1.70%)          56.27
8   9  Nov 21 2019  ...      N/A (N/A)          66.40
9  10  Nov 21 2019  ...   3.60 (2.78%)         123.71

[10 rows x 19 columns]

In [14]:
df.tail(20)

          no         date  ... Dividend Yield  1Y target est
67885  67886  Apr 28 2020  ...   3.08 (3.43%)            NaN
67886  67887  Apr 28 2020  ...      N/A (N/A)         192.81
67887  67888  Apr 28 2020  ...      N/A (N/A)         100.31
67888  67889  Apr 28 2020  ...      N/A (N/A)          15.33
67889  67890  Apr 28 2020  ...      N/A (N/A)          36.00
67890  67891  Apr 28 2020  ...      N/A (N/A)          45.50
67891  67892  Apr 28 2020  ...   0.04 (0.34%)          60.52
67892  67893  Apr 28 2020  ...      N/A (N/A)          82.00
67893  67894  Apr 28 2020  ...      N/A (N/A)          29.67
67894  67895  Apr 28 2020  ...      N/A (N/A)          58.33
67895  67896  Apr 28 2020  ...      N/A (N/A)         137.25
67896  67897  Apr 28 2020  ...   0.64 (2.95%)          24.00
67897  67898  Apr 28 2020  ...   0.32 (1.21%)          34.13
67898  67899  Apr 28 2020  ...      N/A (N/A)          28.00
67899  67900  Apr 28 2020  ...      N/A (N/A)          66.75
67900  67901  Apr 28 2020  ...      N/A (N/A)          12.83
67901  67902  Apr 28 2020  ...   0.44 (1.49%)          33.33
67902  67903  Apr 28 2020  ...      N/A (N/A)          11.50
67903  67904  Apr 28 2020  ...      N/A (N/A)          67.67
67904  67905  Apr 28 2020  ...      N/A (N/A)          67.62

[20 rows x 19 columns]

In [15]:
df.columns

Index(['no', 'date', 'company_name', 'price_at_close', 'price_change',
       'price_after_hours', 'previous_close', 'today opened', 'price range',
       '52 week range', 'volume', 'average volume', 'market cap',
       'beta (3Y Monthly)', 'PE Ratio', 'EPS', 'earnings date',
       'Dividend Yield', '1Y target est'],
      dtype='object')

In [16]:
print(df.columns)

Index(['no', 'date', 'company_name', 'price_at_close', 'price_change',
       'price_after_hours', 'previous_close', 'today opened', 'price range',
       '52 week range', 'volume', 'average volume', 'market cap',
       'beta (3Y Monthly)', 'PE Ratio', 'EPS', 'earnings date',
       'Dividend Yield', '1Y target est'],
      dtype='object')

In [17]:
type(df)

pandas.core.frame.DataFrame

In [18]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [19]:
df.shape

(67905, 19)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67905 entries, 0 to 67904
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   no                 67905 non-null  int64
 1   date               67905 non-null  object
 2   company_name       67905 non-null  object
 3   price_at_close     67761 non-null  float64
 4   price_change       67761 non-null  object
 5   price_after_hours  67761 non-null  float64
 6   previous_close     67761 non-null  float64
 7   today opened       67750 non-null  float64
 8   price range        67756 non-null  object
 9   52 week range      67657 non-null  object
 10  volume             67752 non-null  object
 11  average volume     66584 non-null  float64
 12  market cap         67298 non-null  object
 13  beta (3Y Monthly)  63163 non-null  float64
 14  PE Ratio           60220 non-null  float64
 15  EPS                64962 non-null  float64
 16  earnings date      57611 non-null  object
 17  Dividend Yield     67625 non-null  object
 18  1Y target est      57931 non-null  float64
dtypes: float64(9), int64(1), object(9)
memory usage: 9.8+ MB

In [21]:
df.groupby('company_name')['price_at_close'].mean()

company_name
A - Agilent Technologies, Inc.           79.074615
AAL -                                    16.040000
AAL - American Airlines Group Inc.       20.505844
AAP -                                   126.920000
AAP - Advance Auto Parts, Inc.          127.387532
                                           ...
ZS -                                     52.693333
ZS - Zscaler, Inc.                       58.650500
ZTS - Zoetis Inc.                       128.024889
ZYNE -                                    4.163333
ZYNE - Zynerba Pharmaceuticals, Inc.      4.222143
Name: price_at_close, Length: 1486, dtype: float64

In [22]:
df.groupby(['company_name', 'date'])[['price_at_close', 'price_change']].mean()

                                                  price_at_close
company_name                         date
A - Agilent Technologies, Inc.       Apr 01 2020           68.92
                                     Apr 02 2020           72.29
                                     Apr 03 2020           70.42
                                     Apr 06 2020           74.36
                                     Apr 07 2020           74.03
...                                                          ...
ZYNE - Zynerba Pharmaceuticals, Inc. Mar 19 2020            3.10
                                     Mar 20 2020            3.25
                                     Mar 24 2020            3.76
                                     Mar 25 2020            3.83
                                     Mar 30 2020            3.67

[67898 rows x 1 columns]